#!/bin/bash
set -euxo pipefail
# shellcheck disable=SC2154
rm -rf "${venv}" && \
curl --silent --location --output /tmp/virtualenv.pyz https://bootstrap.pypa.io/virtualenv.pyz && \
python3 /tmp/virtualenv.pyz "${venv}" && \
rm -rf /tmp/virtualenv.pyz
echo  # an empty line here so the next line will be the last.
echo "changed=yes comment='installed bootstrap venv in to venv=${venv}'"
